"""
Project Euler: Problem 2

"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

First we must construct a list of the Fibonacci numbers.
"""

fibs = [1, 2]

while (fibs[-1] + fibs[-2]) < 4000000:
    fibs.append((fibs[-1] + fibs[-2]))

"""
The sum of the even numbers can be found by summing the elements of the list with modulo equal to zero.
"""

evens = sum(x for x in fibs if x % 2 == 0)

print(evens)